version: '3.8'

services:
  postgres:
    image: postgres:16.3
    container_name: realestatebooking-postgres
    environment:
      POSTGRES_DB: realestatebooking
      POSTGRES_USER: potest
      POSTGRES_PASSWORD: potest
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"
volumes:
  postgres-data:
  pgadmin: