version: '3.8'

services:
  app:
    build: .
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/realestatebooking
      DB_USERNAME: potest
      DB_PASSWORD: potest
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:16.3
    container_name: realestatebooking-postgres
    environment:
      POSTGRES_DB: realestatebooking
      POSTGRES_USER: potest
      POSTGRES_PASSWORD: potest
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
volumes:
  postgres-data:
  pgadmin:
  prometheus-data:
  grafana-data: