spring.application.name=Real Estate Booking

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Prometeus and Grafana
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
